<?php

namespace Database\Seeders;

use App\Models\RecomCropBreed;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PhilippineCropVarietiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Populates the database with Philippine corn and rice varieties.
     */
    public function run(): void
    {
        // Get the first user ID for demo purposes, or use 1 as default
        $userId = DB::table('users')->first()?->id ?? 1;

        $varieties = [
            // =====================================================
            // RICE (PALAY) - INBRED VARIETIES
            // =====================================================
            [
                'usersId' => $userId,
                'name' => 'NSIC Rc222 (Tubigan 18)',
                'cropType' => 'rice',
                'breedType' => 'inbred',
                'cornType' => null,
                'manufacturer' => 'PhilRice',
                'potentialYield' => '6.0-7.5 tons/ha',
                'maturityDays' => '112-118 days',
                'geneProtection' => ['Blast', 'Bacterial Leaf Blight'],
                'characteristics' => 'Semi-dwarf, intermediate tillering, long slender grain, good eating quality',
                'relatedInformation' => 'One of the most popular inbred rice varieties in the Philippines. Suitable for irrigated lowland conditions.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'NSIC Rc160 (Tubigan 14)',
                'cropType' => 'rice',
                'breedType' => 'inbred',
                'cornType' => null,
                'manufacturer' => 'PhilRice',
                'potentialYield' => '5.5-7.0 tons/ha',
                'maturityDays' => '110-115 days',
                'geneProtection' => ['Bacterial Leaf Blight', 'Tungro'],
                'characteristics' => 'Semi-dwarf plant type, good grain quality, aromatic',
                'relatedInformation' => 'Widely adapted to different lowland conditions. Known for its aromatic quality.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'NSIC Rc216',
                'cropType' => 'rice',
                'breedType' => 'inbred',
                'cornType' => null,
                'manufacturer' => 'PhilRice',
                'potentialYield' => '5.8-7.2 tons/ha',
                'maturityDays' => '115-120 days',
                'geneProtection' => ['Blast', 'Brown Planthopper'],
                'characteristics' => 'Semi-dwarf, intermediate amylose content, long grain',
                'relatedInformation' => 'Good for both wet and dry seasons. Resistant to major pests.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'NSIC Rc218',
                'cropType' => 'rice',
                'breedType' => 'inbred',
                'cornType' => null,
                'manufacturer' => 'PhilRice',
                'potentialYield' => '6.0-7.0 tons/ha',
                'maturityDays' => '113-118 days',
                'geneProtection' => ['Bacterial Leaf Blight', 'Tungro', 'Brown Planthopper'],
                'characteristics' => 'Semi-dwarf, good tillering ability, long slender grain',
                'relatedInformation' => 'Multiple disease resistance makes it ideal for areas with high pest pressure.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'NSIC Rc402 (Sahod Ulan 1)',
                'cropType' => 'rice',
                'breedType' => 'inbred',
                'cornType' => null,
                'manufacturer' => 'PhilRice',
                'potentialYield' => '4.5-5.5 tons/ha',
                'maturityDays' => '105-110 days',
                'geneProtection' => ['Drought Tolerance', 'Blast'],
                'characteristics' => 'Drought-tolerant, short duration, good recovery after stress',
                'relatedInformation' => 'Specifically developed for rainfed lowland areas with drought occurrence.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'NSIC Rc442',
                'cropType' => 'rice',
                'breedType' => 'inbred',
                'cornType' => null,
                'manufacturer' => 'PhilRice',
                'potentialYield' => '5.5-6.5 tons/ha',
                'maturityDays' => '115-120 days',
                'geneProtection' => ['Submergence Tolerance', 'Bacterial Leaf Blight'],
                'characteristics' => 'Submergence tolerant up to 14 days, good recovery, medium grain',
                'relatedInformation' => 'Ideal for flood-prone areas. Can survive complete submergence.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'PSB Rc82',
                'cropType' => 'rice',
                'breedType' => 'inbred',
                'cornType' => null,
                'manufacturer' => 'PhilRice',
                'potentialYield' => '5.0-6.5 tons/ha',
                'maturityDays' => '116-120 days',
                'geneProtection' => ['Blast', 'Bacterial Leaf Blight'],
                'characteristics' => 'Semi-dwarf, excellent grain quality, aromatic',
                'relatedInformation' => 'Known for premium grain quality. Popular in Central Luzon.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'PSB Rc18',
                'cropType' => 'rice',
                'breedType' => 'inbred',
                'cornType' => null,
                'manufacturer' => 'PhilRice',
                'potentialYield' => '5.5-7.0 tons/ha',
                'maturityDays' => '112-117 days',
                'geneProtection' => ['Tungro', 'Blast'],
                'characteristics' => 'Semi-dwarf, good tillering, long slender grain',
                'relatedInformation' => 'Widely adapted variety with stable yields across environments.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'NSIC Rc436',
                'cropType' => 'rice',
                'breedType' => 'inbred',
                'cornType' => null,
                'manufacturer' => 'PhilRice',
                'potentialYield' => '5.0-6.0 tons/ha',
                'maturityDays' => '108-112 days',
                'geneProtection' => ['Salinity Tolerance', 'Blast'],
                'characteristics' => 'Salt-tolerant, early maturing, medium grain',
                'relatedInformation' => 'Suitable for coastal areas with saline soils.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'IR64',
                'cropType' => 'rice',
                'breedType' => 'inbred',
                'cornType' => null,
                'manufacturer' => 'IRRI',
                'potentialYield' => '5.0-6.5 tons/ha',
                'maturityDays' => '110-115 days',
                'geneProtection' => ['Blast', 'Brown Planthopper'],
                'characteristics' => 'Semi-dwarf, excellent cooking quality, long slender grain',
                'relatedInformation' => 'Classic variety developed by IRRI. Still popular for its grain quality.',
                'isActive' => true,
                'delete_status' => 'active',
            ],

            // =====================================================
            // RICE (PALAY) - HYBRID VARIETIES
            // =====================================================
            [
                'usersId' => $userId,
                'name' => 'Mestizo 1 (NSIC Rc9H)',
                'cropType' => 'rice',
                'breedType' => 'hybrid',
                'cornType' => null,
                'manufacturer' => 'PhilRice / SL Agritech',
                'potentialYield' => '8.0-10.0 tons/ha',
                'maturityDays' => '115-120 days',
                'geneProtection' => ['Blast', 'Bacterial Leaf Blight', 'Tungro'],
                'characteristics' => 'High yielding hybrid, semi-dwarf, excellent tillering',
                'relatedInformation' => 'First commercial hybrid rice in the Philippines. High yield potential.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'Mestizo 7 (SL-7H)',
                'cropType' => 'rice',
                'breedType' => 'hybrid',
                'cornType' => null,
                'manufacturer' => 'SL Agritech',
                'potentialYield' => '8.5-11.0 tons/ha',
                'maturityDays' => '113-118 days',
                'geneProtection' => ['Blast', 'Bacterial Leaf Blight'],
                'characteristics' => 'Very high yield, good grain quality, strong culm',
                'relatedInformation' => 'Popular hybrid known for consistent high yields.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'Mestizo 19 (SL-19H)',
                'cropType' => 'rice',
                'breedType' => 'hybrid',
                'cornType' => null,
                'manufacturer' => 'SL Agritech',
                'potentialYield' => '9.0-12.0 tons/ha',
                'maturityDays' => '115-120 days',
                'geneProtection' => ['Blast', 'Bacterial Leaf Blight', 'Brown Planthopper'],
                'characteristics' => 'Highest yielding Mestizo series, premium grain quality',
                'relatedInformation' => 'Latest in the Mestizo series with improved yield and quality.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'PHB 71',
                'cropType' => 'rice',
                'breedType' => 'hybrid',
                'cornType' => null,
                'manufacturer' => 'Pioneer Hi-Bred',
                'potentialYield' => '8.0-10.5 tons/ha',
                'maturityDays' => '110-115 days',
                'geneProtection' => ['Blast', 'Tungro'],
                'characteristics' => 'High yield, early maturity, good grain quality',
                'relatedInformation' => 'Popular Pioneer hybrid with proven performance.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'PHB 77',
                'cropType' => 'rice',
                'breedType' => 'hybrid',
                'cornType' => null,
                'manufacturer' => 'Pioneer Hi-Bred',
                'potentialYield' => '8.5-11.0 tons/ha',
                'maturityDays' => '112-118 days',
                'geneProtection' => ['Blast', 'Bacterial Leaf Blight', 'Brown Planthopper'],
                'characteristics' => 'Improved yield over PHB 71, excellent tillering',
                'relatedInformation' => 'Advanced Pioneer hybrid with enhanced disease resistance.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'Bigante Plus',
                'cropType' => 'rice',
                'breedType' => 'hybrid',
                'cornType' => null,
                'manufacturer' => 'SL Agritech',
                'potentialYield' => '9.0-12.0 tons/ha',
                'maturityDays' => '115-122 days',
                'geneProtection' => ['Blast', 'Tungro', 'Brown Planthopper'],
                'characteristics' => 'Extra large grain, very high yield, strong stalks',
                'relatedInformation' => 'Premium hybrid known for big grains and high yields.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'Sterling',
                'cropType' => 'rice',
                'breedType' => 'hybrid',
                'cornType' => null,
                'manufacturer' => 'Bayer CropScience',
                'potentialYield' => '8.0-10.0 tons/ha',
                'maturityDays' => '112-117 days',
                'geneProtection' => ['Blast', 'Bacterial Leaf Blight'],
                'characteristics' => 'High yield, good milling recovery, premium grain',
                'relatedInformation' => 'Bayer hybrid with excellent grain quality characteristics.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'TH82',
                'cropType' => 'rice',
                'breedType' => 'hybrid',
                'cornType' => null,
                'manufacturer' => 'Tropigen Seeds',
                'potentialYield' => '7.5-9.5 tons/ha',
                'maturityDays' => '108-115 days',
                'geneProtection' => ['Blast', 'Tungro'],
                'characteristics' => 'Early maturing hybrid, good adaptation, medium grain',
                'relatedInformation' => 'Good for tri-cropping due to early maturity.',
                'isActive' => true,
                'delete_status' => 'active',
            ],

            // =====================================================
            // YELLOW CORN - HYBRID VARIETIES
            // =====================================================
            [
                'usersId' => $userId,
                'name' => 'Dekalb DK818',
                'cropType' => 'corn',
                'breedType' => 'hybrid',
                'cornType' => 'yellow',
                'manufacturer' => 'Bayer (Monsanto)',
                'potentialYield' => '8.0-12.0 tons/ha',
                'maturityDays' => '110-120 days',
                'geneProtection' => ['Downy Mildew', 'Corn Borer (Bt)'],
                'characteristics' => 'High yielding, excellent standability, deep kernels',
                'relatedInformation' => 'Popular Dekalb variety with Bt technology for corn borer protection.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'Dekalb DK6919S',
                'cropType' => 'corn',
                'breedType' => 'hybrid',
                'cornType' => 'yellow',
                'manufacturer' => 'Bayer (Monsanto)',
                'potentialYield' => '9.0-13.0 tons/ha',
                'maturityDays' => '115-125 days',
                'geneProtection' => ['Downy Mildew', 'Corn Borer (Bt)', 'Herbicide Tolerance'],
                'characteristics' => 'Premium yield, strong stalk, excellent tip fill',
                'relatedInformation' => 'Stacked trait variety with Bt and herbicide tolerance.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'Pioneer P3228',
                'cropType' => 'corn',
                'breedType' => 'hybrid',
                'cornType' => 'yellow',
                'manufacturer' => 'Pioneer Hi-Bred (Corteva)',
                'potentialYield' => '8.5-11.5 tons/ha',
                'maturityDays' => '108-118 days',
                'geneProtection' => ['Downy Mildew', 'Stalk Rot'],
                'characteristics' => 'Good standability, excellent grain quality, consistent yield',
                'relatedInformation' => 'Pioneer classic with proven field performance.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'Pioneer P3396',
                'cropType' => 'corn',
                'breedType' => 'hybrid',
                'cornType' => 'yellow',
                'manufacturer' => 'Pioneer Hi-Bred (Corteva)',
                'potentialYield' => '9.0-12.5 tons/ha',
                'maturityDays' => '112-122 days',
                'geneProtection' => ['Downy Mildew', 'Corn Borer', 'Ear Rot'],
                'characteristics' => 'High yield potential, excellent ear size, deep orange kernels',
                'relatedInformation' => 'Advanced Pioneer hybrid for high-input farming.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'Syngenta NK8328',
                'cropType' => 'corn',
                'breedType' => 'hybrid',
                'cornType' => 'yellow',
                'manufacturer' => 'Syngenta',
                'potentialYield' => '8.0-11.0 tons/ha',
                'maturityDays' => '105-115 days',
                'geneProtection' => ['Downy Mildew', 'Stalk Rot'],
                'characteristics' => 'Early maturity, good drought tolerance, strong roots',
                'relatedInformation' => 'Versatile variety suitable for various conditions.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'Syngenta NK6410',
                'cropType' => 'corn',
                'breedType' => 'hybrid',
                'cornType' => 'yellow',
                'manufacturer' => 'Syngenta',
                'potentialYield' => '8.5-12.0 tons/ha',
                'maturityDays' => '110-120 days',
                'geneProtection' => ['Downy Mildew', 'Corn Borer (Bt)'],
                'characteristics' => 'Bt technology, excellent yield, good husk cover',
                'relatedInformation' => 'Syngenta Bt corn for corn borer-prone areas.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'Bioseed 9909',
                'cropType' => 'corn',
                'breedType' => 'hybrid',
                'cornType' => 'yellow',
                'manufacturer' => 'Bioseed',
                'potentialYield' => '7.5-10.5 tons/ha',
                'maturityDays' => '105-115 days',
                'geneProtection' => ['Downy Mildew'],
                'characteristics' => 'Good adaptability, medium height, consistent yield',
                'relatedInformation' => 'Affordable hybrid option with good performance.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'Advanta Pacific 339',
                'cropType' => 'corn',
                'breedType' => 'hybrid',
                'cornType' => 'yellow',
                'manufacturer' => 'Advanta Seeds',
                'potentialYield' => '8.0-11.0 tons/ha',
                'maturityDays' => '108-118 days',
                'geneProtection' => ['Downy Mildew', 'Ear Rot'],
                'characteristics' => 'Good ear placement, strong stalks, orange kernels',
                'relatedInformation' => 'Reliable hybrid for lowland conditions.',
                'isActive' => true,
                'delete_status' => 'active',
            ],

            // =====================================================
            // WHITE CORN VARIETIES
            // =====================================================
            [
                'usersId' => $userId,
                'name' => 'Tiniguib',
                'cropType' => 'corn',
                'breedType' => 'opv',
                'cornType' => 'white',
                'manufacturer' => 'Traditional / UPLB',
                'potentialYield' => '3.0-4.5 tons/ha',
                'maturityDays' => '95-105 days',
                'geneProtection' => ['General Adaptation'],
                'characteristics' => 'Traditional OPV, soft endosperm, good for food',
                'relatedInformation' => 'Popular traditional white corn for human consumption in Visayas and Mindanao.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'IPB Var 4 (Glutinous)',
                'cropType' => 'corn',
                'breedType' => 'opv',
                'cornType' => 'special',
                'manufacturer' => 'UPLB - IPB',
                'potentialYield' => '3.5-5.0 tons/ha',
                'maturityDays' => '90-100 days',
                'geneProtection' => ['Downy Mildew Tolerance'],
                'characteristics' => 'Glutinous/waxy corn, sweet taste, soft texture',
                'relatedInformation' => 'Special purpose corn for food products. Popular for corn-on-cob.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'Native White (Mindanao)',
                'cropType' => 'corn',
                'breedType' => 'opv',
                'cornType' => 'white',
                'manufacturer' => 'Traditional',
                'potentialYield' => '2.5-4.0 tons/ha',
                'maturityDays' => '90-100 days',
                'geneProtection' => ['Local Adaptation'],
                'characteristics' => 'Traditional variety, soft texture, for human consumption',
                'relatedInformation' => 'Staple food crop in Mindanao, used for corn grits.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'Lagkitan',
                'cropType' => 'corn',
                'breedType' => 'opv',
                'cornType' => 'special',
                'manufacturer' => 'Traditional',
                'potentialYield' => '3.0-4.0 tons/ha',
                'maturityDays' => '85-95 days',
                'geneProtection' => ['General Adaptation'],
                'characteristics' => 'Glutinous/sticky corn, early maturing',
                'relatedInformation' => 'Traditional glutinous corn popular in Visayas region.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'USM Var 5',
                'cropType' => 'corn',
                'breedType' => 'opv',
                'cornType' => 'white',
                'manufacturer' => 'University of Southern Mindanao',
                'potentialYield' => '4.0-5.5 tons/ha',
                'maturityDays' => '95-105 days',
                'geneProtection' => ['Downy Mildew Tolerance'],
                'characteristics' => 'Improved OPV, higher yield than traditional varieties',
                'relatedInformation' => 'Developed for Mindanao conditions, improved white corn.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'Sweet Corn - Sugar King',
                'cropType' => 'corn',
                'breedType' => 'hybrid',
                'cornType' => 'special',
                'manufacturer' => 'East-West Seed',
                'potentialYield' => '10-15 tons/ha (fresh ears)',
                'maturityDays' => '70-75 days',
                'geneProtection' => ['General Tolerance'],
                'characteristics' => 'High sugar content, tender kernels, excellent sweetness',
                'relatedInformation' => 'Premium sweet corn variety for fresh market.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
            [
                'usersId' => $userId,
                'name' => 'Sweet Corn - Pacific 421',
                'cropType' => 'corn',
                'breedType' => 'hybrid',
                'cornType' => 'special',
                'manufacturer' => 'Advanta Seeds',
                'potentialYield' => '12-16 tons/ha (fresh ears)',
                'maturityDays' => '72-78 days',
                'geneProtection' => ['Downy Mildew Tolerance'],
                'characteristics' => 'Super sweet, excellent tip fill, uniform ears',
                'relatedInformation' => 'Popular sweet corn for commercial production.',
                'isActive' => true,
                'delete_status' => 'active',
            ],
        ];

        foreach ($varieties as $variety) {
            RecomCropBreed::create($variety);
        }

        $this->command->info('Philippine crop varieties seeded successfully! (' . count($varieties) . ' varieties)');
    }
}
