@extends('layouts.master')

@section('title') Schemas @endsection

@section('content')
@component('components.breadcrumb')
@slot('li_1') TouristGuidePh @endslot
@slot('title') Schemas @endslot
@endcomponent

<div class="card mb-3">
    <div class="card-body">
        <h5 class="card-title mb-2">Auto-emitted JSON-LD schemas</h5>
        <p class="text-muted small mb-3">These schemas are generated by the frontend on every request. They adapt to dynamic data
            (listings, reviews, FAQs, author dates) without any manual maintenance.</p>
        <div class="table-responsive">
            <table class="table table-bordered table-sm">
                <thead class="table-light">
                    <tr><th style="width:200px">Schema type</th><th style="width:200px">Scope</th><th>Built from</th><th style="width:140px">Dynamic</th></tr>
                </thead>
                <tbody>
                    @foreach($autoEmitted as $row)
                        <tr>
                            <td><code class="text-primary">{{ $row['type'] }}</code></td>
                            <td>{{ $row['scope'] }}</td>
                            <td class="small">{{ $row['source'] }}</td>
                            <td><small class="{{ str_starts_with($row['dynamic'], 'YES') ? 'text-success fw-bold' : 'text-muted' }}">{{ $row['dynamic'] }}</small></td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h5 class="card-title mb-3">Custom schema overrides (per SEO page)</h5>
        <p class="text-muted small mb-3">Each SEO page has a <code>schema_json</code> column that lets you inject additional
            JSON-LD beyond the auto-emitted ones. The custom JSON is merged into the page's <code>&lt;script type="application/ld+json"&gt;</code>
            tags alongside the dynamic schemas above.</p>

        @if($pagesWithCustomSchema->isEmpty())
            <div class="text-center text-muted py-4">
                <i class="bx bx-code-curly" style="font-size:48px"></i>
                <p class="mt-2 mb-0">No pages have custom schema overrides yet.</p>
                <p class="small">Open any SEO page in the Keywords module to add one, or use the form below to pick a page.</p>
            </div>
        @else
            <div class="table-responsive">
                <table class="table table-sm table-hover align-middle">
                    <thead class="table-light">
                        <tr><th>Page</th><th>Slug</th><th>JSON length</th><th style="width:280px">Actions</th></tr>
                    </thead>
                    <tbody>
                        @foreach($pagesWithCustomSchema as $p)
                            <tr>
                                <td>{{ $p->title }}</td>
                                <td><code>/{{ $p->slug }}</code></td>
                                <td>{{ number_format(strlen($p->schema_json)) }} chars</td>
                                <td>
                                    <a href="/resort-guru-schemas-edit?id={{ $p->id }}" class="btn btn-sm btn-outline-primary"><i class="bx bx-edit"></i> Edit JSON</a>
                                    <a href="/resort-guru-schemas-preview?id={{ $p->id }}" class="btn btn-sm btn-outline-info"><i class="bx bx-show"></i> Live preview</a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        @endif

        <hr class="my-4">
        <h6 class="mb-3">Add or edit a custom schema for any page</h6>
        <form method="GET" action="/resort-guru-schemas-edit" class="d-flex gap-2 align-items-end">
            <div class="flex-grow-1">
                <label class="form-label small mb-1">Pick a page</label>
                <select name="id" class="form-select form-select-sm">
                    @foreach(\Illuminate\Support\Facades\DB::table('rg_seo_pages')->orderBy('slug')->get(['id','slug','title']) as $p)
                        <option value="{{ $p->id }}">{{ $p->slug }} — {{ $p->title }}</option>
                    @endforeach
                </select>
            </div>
            <button type="submit" class="btn btn-sm btn-primary"><i class="bx bx-code-curly me-1"></i>Open editor</button>
        </form>
    </div>
</div>
@endsection
