<?php

namespace App\Models;

class AiChatSession extends BaseModel
{
    protected $table = 'ai_chat_sessions';

    protected $fillable = [
        'usersId',
        'sessionName',
        'replyFlowId',
        'lastMessageAt',
        'messageCount',
        'metadata',
        'delete_status',
    ];

    protected $casts = [
        'lastMessageAt' => 'datetime',
        'messageCount' => 'integer',
        'metadata' => 'array',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
    ];

    // ==================== SCOPES ====================

    /**
     * Scope for active records.
     */
    public function scopeActive($query)
    {
        return $query->where('delete_status', 'active');
    }

    /**
     * Scope for user's records.
     */
    public function scopeForUser($query, $userId)
    {
        return $query->where('usersId', $userId);
    }

    // ==================== RELATIONSHIPS ====================

    /**
     * Get the user that owns the session.
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'usersId');
    }

    /**
     * Get the reply flow used for this session.
     */
    public function replyFlow()
    {
        return $this->belongsTo(AiReplyFlow::class, 'replyFlowId');
    }

    /**
     * Get all messages in this session.
     */
    public function messages()
    {
        return $this->hasMany(AiChatMessage::class, 'sessionId')
            ->where('delete_status', 'active')
            ->orderBy('created_at', 'asc');
    }

    /**
     * Get the last message in this session.
     */
    public function lastMessage()
    {
        return $this->hasOne(AiChatMessage::class, 'sessionId')
            ->where('delete_status', 'active')
            ->latest();
    }

    // ==================== COMPUTED ATTRIBUTES ====================

    /**
     * Get display name for the session.
     */
    public function getDisplayNameAttribute()
    {
        if ($this->sessionName) {
            return $this->sessionName;
        }

        // Use first message content as name
        $firstMessage = $this->messages()->first();
        if ($firstMessage) {
            return \Str::limit($firstMessage->content, 40);
        }

        return 'New Chat';
    }

    /**
     * Get time ago format for last message.
     */
    public function getLastMessageAgoAttribute()
    {
        if ($this->lastMessageAt) {
            return $this->lastMessageAt->diffForHumans();
        }
        return $this->created_at->diffForHumans();
    }

    // ==================== HELPER METHODS ====================

    /**
     * Increment message count and update last message time.
     */
    public function recordNewMessage()
    {
        $this->increment('messageCount');
        $this->update(['lastMessageAt' => now()]);
    }

    /**
     * Get metadata value.
     */
    public function getMeta(string $key, $default = null)
    {
        return $this->metadata[$key] ?? $default;
    }

    /**
     * Set metadata value.
     */
    public function setMeta(string $key, $value): void
    {
        $metadata = $this->metadata ?? [];
        $metadata[$key] = $value;
        $this->update(['metadata' => $metadata]);
    }

    /**
     * Get user gender.
     */
    public function getUserGender(): ?string
    {
        return $this->getMeta('userGender');
    }

    /**
     * Set user gender.
     */
    public function setUserGender(string $gender): void
    {
        $this->setMeta('userGender', $gender);
    }

    /**
     * Get conversation state.
     */
    public function getConversationState(): string
    {
        return $this->getMeta('conversationState', 'new');
    }

    /**
     * Set conversation state.
     */
    public function setConversationState(string $state): void
    {
        $this->setMeta('conversationState', $state);
    }

    /**
     * Check if this is a new session (no messages yet).
     */
    public function isNewSession(): bool
    {
        return $this->messageCount == 0 || $this->getConversationState() === 'new';
    }

    /**
     * Check if we're awaiting gender response.
     */
    public function isAwaitingGender(): bool
    {
        return $this->getConversationState() === 'awaiting_gender';
    }

    /**
     * Check if title has been AI-generated.
     */
    public function isTitleGenerated(): bool
    {
        return $this->getMeta('titleGenerated', false) === true;
    }

    /**
     * Mark title as AI-generated.
     */
    public function markTitleGenerated(): void
    {
        $this->setMeta('titleGenerated', true);
    }

    /**
     * Check if title needs generation (not yet generated by AI).
     */
    public function needsTitleGeneration(): bool
    {
        return !$this->isTitleGenerated();
    }

    /**
     * Get chat history formatted for AI context.
     */
    public function getChatHistoryForAI($limit = 20)
    {
        $messages = $this->messages()
            ->whereIn('role', ['user', 'assistant'])
            ->latest()
            ->take($limit)
            ->get()
            ->reverse();

        $history = [];
        foreach ($messages as $msg) {
            $history[] = [
                'role' => $msg->role,
                'content' => $msg->content,
            ];
        }

        return $history;
    }

    /**
     * Get chat history as text for merge fields.
     */
    public function getChatHistoryText($limit = 10)
    {
        $messages = $this->messages()
            ->whereIn('role', ['user', 'assistant'])
            ->latest()
            ->take($limit)
            ->get()
            ->reverse();

        $text = '';
        foreach ($messages as $msg) {
            $role = ucfirst($msg->role);
            $text .= "{$role}: {$msg->content}\n\n";
        }

        return trim($text);
    }
}
